Add vsetvli to indicate vl and policy in vcompress example.
riscv/riscv-v-spec pull request #789
Opened 2022-04-21 02:19 UTC by zakk0610

I think it could make reader aware that "The remaining elements of vd are treated as tail elements according to the current tail policy"

2022-04-21 02:25 UTC, nick-knight requested changes

2022-04-21 02:25 UTC, nick-knight commented on v-spec.adoc
> +                                vsetvli      t0, 8, e8, m1, tu, ta
```suggestion
                                vsetivli      t0, 9, e8, m1, tu, ma
```

2022-04-21 03:48 UTC, zakk0610 commented on v-spec.adoc
> +                                vsetvli      t0, 8, e8, m1, tu, ta
Thanks!!  typo fixed.

2022-04-21 04:03 UTC, nick-knight requested changes
@Zakk, you only made one of my three suggested changes. I'm curious if you disagree with my other two. Here they are again.

2022-04-21 04:03 UTC, nick-knight commented on v-spec.adoc
> +                                vsetvli      t0, 8, e8, m1, tu, ma
```suggestion
                                vsetivli      t0, 9, e8, m1, tu, ma
```

2022-04-21 04:30 UTC, zakk0610 commented on v-spec.adoc
> +                                vsetvli      t0, 8, e8, m1, tu, ma
My bad, I agree with you. Thanks again.

2022-12-16 22:49 UTC, nick-knight approved these changes

2022-12-17 00:05 UTC, aswaterman approved these changes

2022-12-17 00:06 UTC, merged